# FOR TESTS
version: "3.7"

services:
  # Runs Vue unit tests
  app-unit-test:
    image: node:12
    command: npm run test:unit
    working_dir: /home/node
    volumes:
      - ../web:/home/node
  
  # Runs python unit tests
  api-test:
    image: python:3.8
    command: python manage.py test -v 2 --no-input
    working_dir: /app
    environment:
      VIRTUAL_ENV: /app/env
      PATH: /app/env/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ../api/tacticalrmm:/app
    depends_on: 
      - db
      - redis
      - venv
    networks:
      - database
      - redis

  # Builds Python Virtual Env to share between containers
  venv:
    image: python:3.8
    command: /bin/bash -c "pip install virtualenv && python -m virtualenv env && ./env/bin/pip install -r requirements.txt && ./env/bin/pip install -r requirements-dev.txt"
    working_dir: /app
    volumes:
      - ../api/tacticalrmm:/app
